name: Cache Task Workflow
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create dummy file for caching
        run: |
          mkdir -p my-cache-dir
          echo "Caching this content" > my-cache-dir/content.txt
      - name: Setup Cache
        id: cache-step
        uses: actions/cache@v4
        with:
          path: my-cache-dir
          key: cache-0ca11d7
      - name: prime-cache-0ca11d7
        run: echo "Cache hit: ${{ steps.cache-step.outputs.cache-hit }}"
